# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-11-24 06:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Usermeta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.IntegerField(unique=True, verbose_name='用户ID')),
                ('key', models.CharField(max_length=20, unique=True, verbose_name='key')),
                ('value', models.CharField(max_length=20, verbose_name='value')),
            ],
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('login', models.CharField(max_length=15, unique=True, verbose_name='用户名')),
                ('passw', models.CharField(max_length=30, verbose_name='密码')),
                ('nickname', models.CharField(max_length=15, unique=True, verbose_name='昵称')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='邮箱')),
                ('url', models.URLField(null=True, verbose_name='网址')),
                ('registered', models.DateTimeField(auto_now_add=True, verbose_name='注册时间')),
                ('status', models.IntegerField(choices=[('0', '正常'), ('1', '封禁'), ('9', '删除')], default=0, verbose_name='账户状态')),
            ],
        ),
    ]
